### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by Light2288**
change to version 1.1.8

### CODE REVIEW

**Review by astagi — CHANGES_REQUESTED** [review]
@Light2288 1.1.6 -> 1.1.8 why?

**Comment by Light2288** [comment]
> @Light2288 1.1.6 -> 1.1.8 why?

@astagi yes, version 1.1.7 was already released to fix a minor bug on Android sdk for school mode (without changes on app side). Unfortunately due to the urgency of the following releases (remove work and school mode only on the app side), i forgot to create the release branch; I just created branch https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feat/change-version-117, I can generate a release tag and branch from here if it is ok for you, sorry I apologise for the inconvenience

**Comment by astagi** [comment]
> > @Light2288 1.1.6 -> 1.1.8 why?
> 
> @astagi yes, version 1.1.7 was already released to fix a minor bug on Android sdk for school mode (without changes on app side). Unfortunately due to the urgency of the following releases (remove work and school mode only on the app side), i forgot to create the release branch; I just created branch https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feat/change-version-117, I can generate a release tag and branch from here if it is ok for you, sorry I apologise for the inconvenience

No problem @Light2288 yes please generate a release tag and branch from there, just to keep a coherent history. Then I'll merge this PR and update our CHANGELOG

**Comment by Light2288** [comment]
> > > @Light2288 1.1.6 -> 1.1.8 why?
> > 
> > 
> > @astagi yes, version 1.1.7 was already released to fix a minor bug on Android sdk for school mode (without changes on app side). Unfortunately due to the urgency of the following releases (remove work and school mode only on the app side), i forgot to create the release branch; I just created branch https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feat/change-version-117, I can generate a release tag and branch from here if it is ok for you, sorry I apologise for the inconvenience
> 
> No problem @Light2288 yes please generate a release tag and branch from there, just to keep a coherent history. Then I'll merge this PR and update our CHANGELOG

@astagi ok I created branch release/1.1.7 and relative tag, thank you

**Comment by astagi** [comment]
Thank you @Light2288

**Comment by astagi** [comment]
@Light2288 in order to keep fixes inside 1.1.7 why not tagging it here https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/7d4debf964d83fead97791e95458706b4e296b56 ? This would be the final changelog

```
## [1.1.8] - 05/04/2022

### Aggiunto

- Nuova modalità di ingresso IT con regole per ingresso a utenti di età inferiore ai 18 anni. Commit di riferimento [qui](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/93e3b64e1d5016f0887b1a153147b35a51d06954)
- Rimozione della modalità lavoro e scuole

## [1.1.7] - 30/03/2022

### Aggiunto

- Aggiunto custom header nelle richieste
- Fix su certificato CBIS
```

**Comment by Light2288** [comment]
> @Light2288 in order to keep fixes inside 1.1.7 why not tagging it here [7d4debf](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/7d4debf964d83fead97791e95458706b4e296b56) ? This would be the final changelog
> 
> ```
> ## [1.1.8] - 05/04/2022
> 
> ### Aggiunto
> 
> - Nuova modalità di ingresso IT con regole per ingresso a utenti di età inferiore ai 18 anni. Commit di riferimento [qui](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/93e3b64e1d5016f0887b1a153147b35a51d06954)
> - Rimozione della modalità lavoro e scuole
> 
> ## [1.1.7] - 30/03/2022
> 
> ### Aggiunto
> 
> - Aggiunto custom header nelle richieste
> - Fix su certificato CBIS
> ```

@astagi yes using this commit would create a more ‘consistente’ release with additional fixes, the commit I already tagged https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/e2da9d7d94075217088561d78c01edcabe12bfd0 is the exact 1.1.7 version that was in production before this 1.1.8 version; no problem in changing the tag and recreate the release branch, just let me know what you prefer

**Comment by astagi** [comment]
Ok @Light2288 ! Yes I'd prefer changing the commit tag and recreate the branch, it's better for developers.

**Comment by astagi** [comment]
changelog updated @Light2288 thank you! when you're ready to tag 1.1.8 let me know, I'll merge changelog as well..

**Comment by Light2288** [comment]
thank you @astagi! [release 1.1.8](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.1.8) and [tag](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/1.1.8) created

**Comment by astagi** [comment]
great! thanks @Light2288

**Pull request merged**
