### PR TITLE
Feature/remove school mode

### PR DESCRIPTION
**Pull request by nicola-95**

### CODE REVIEW

**Review by astagi — CHANGES_REQUESTED** [review]
@nicola-95  please remove line 185 https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/162/files#diff-dc64fe17bfdbce818760f154bcecd09489dc4ce292c522fb6b008bdc0d1b534bR182

**Comment by astagi** [comment]
@nicola-95 ☝🏻

**Comment by nicola-95** [comment]
@astagi, line 185 of `RuleSet.kt`, after commit [bf00373](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/162/commits/bf003732c4c7293a3d1393e5d7c72cf69dabf750), points to `isEma()` method. Is this the change you are pointing out? Do I have to delete this method?

**Comment by astagi** [comment]
> @astagi, line 185 of `RuleSet.kt`, after commit [bf00373](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/162/commits/bf003732c4c7293a3d1393e5d7c72cf69dabf750), points to `isEma()` method. Is this the change you are pointing out? Do I have to delete this method?

no sorry, I'm talking about [validation/VaccineValidationStrategy.kt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/162/files#diff-dc64fe17bfdbce818760f154bcecd09489dc4ce292c522fb6b008bdc0d1b534b) file. There is a line that does nothing, I left a comment on the previous PR https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/161/files#r838488132

**Comment by nicola-95** [comment]
> https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/161/files#r838488132

It's OK, I just deleted that line. Change pushed.

**Comment by astagi** [comment]
> > https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/161/files#r838488132
> 
> It's OK, I just deleted that line. Change pushed.

thank you so much @nicola-95 🙌

**Review by astagi — APPROVED** [review]

**Pull request merged**
