### PR TITLE
feat: add vaccine exemption documentation

### PR DESCRIPTION
**Pull request by Kaizen-7**

### CODE REVIEW

**Review by astagi — APPROVED** [review]

**Comment by astagi** [comment]
@Kaizen-7 please push these changes on `gh-pages` branch as well to make them available online

**Comment by Kaizen-7** [comment]
is "gh-pages" a branch dedicated to documentation? should I merge develop into this branch to keep it up to date with these changes?  @astagi

**Comment by astagi** [comment]
> is "gh-pages" a branch dedicated to documentation? should I merge develop into this branch to keep it up to date with these changes?  @astagi 

Exactly @Kaizen-7

**Comment by Kaizen-7** [comment]
Successfully merged @astagi

**Pull request merged**
